# Base configs
baseurl: "https://ajiwahyu.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Aji Anggoro"
subtitle: "World through The Lens"
author: "Aji Anggoro"
header:
 title: "Photography"
 subtitle: "by Aji Anggoro"
footer:
 name: "Aji is the Name"
 bio: "I am a PhD Candidate in UCLA. Love making life more meaningful through images."
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/ram_patra"
  dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/rampatra"
